import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          className="mobile:border-[1px] broder-border-color rounded 
    w-full max-w-[1440px] min-w-[80vw] mx-auto mt-32">
          {children}
        </main>
      </body>
    </html>
  )
}
